# Generated by Django 5.0.4 on 2024-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_workspace_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_workspace_id',
            field=models.IntegerField(null=True),
        ),
    ]
