# Generated by Django 5.0.4 on 2024-04-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_user_last_workspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_workspace_id',
            field=models.UUIDField(null=True),
        ),
    ]
