name: Deploy to EC2

on:
  push:
    branches:
      - development  # change this to match your main branch name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        sudo apt-get install awscli  # install AWS CLI

    - name: Deploy code to EC2
      run: |
        scp -r * ububtu@43.205.195.234:/home/ubuntu/PLANE/PLANE-DEV/cs-plane-api
        ssh ububtu@43.205.195.234 'cd /home/ubuntu/PLANE/PLANE-DEV/ && \
                                          sudo pip3 install -r requirements.txt && \
                                          sudo python3 manage.py migrate && \
                                          sudo systemctl restart gunicorn.service'  
