name: Django Deployment

on:
  push:
    branches:
      - development  # Adjust the branch as per your setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Run migrations
        run: python manage.py migrate

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance host/IP
          username: ${{ secrets.EC2_USERNAME }}  # SSH username for EC2
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key for authentication
        
          script: |
            cd /home/ubuntu/PLANE/PLANE-DEV/cs-plane-api
            git pull origin development  # Assuming you're pushing to the 'main' branch
            sudo systemctl restart gunicorn  # Restart Gunicorn or whatever your WSGI server is
